### ISSUE TITLE
get "KeyError: 'name'" when using sapp

### ISSUE THREAD

**Issue by mwmarry** [facebook/mariana-trench#166]
Bug description
When using:

`sapp --tool=mariana-trench analyze .`
 
I got error:
$ sapp --tool=mariana-trench analyze .
/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Run.issue_instances to refer to viewonly relationship IssueInstance.run should include sync_backref=False set on the Run.issue_instances relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship IssueInstance.run to refer to viewonly relationship Run.issue_instances should include sync_backref=False set on the IssueInstance.run relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
2024-07-16 14:46:37,192 [INFO] Parsing analysis output...
Traceback (most recent call last):
  File "/home/rong/.venvs/mariana-trench/bin/sapp", line 8, in <module>
    sys.exit(cli())
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/cli_lib.py", line 206, in analyze
    pipeline.run(analysis_output, summary_blob)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/__init__.py", line 365, in run
    next_input, summary = step.run(next_input, summary)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/base_parser.py", line 233, in run
    summary.get("old_linemap_file"),
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/base_parser.py", line 182, in analysis_output_to_dict_entries
    for typ, key, e in self._analysis_output_to_parsed_tuples(inputfile):
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/base_parser.py", line 131, in _analysis_output_to_parsed_tuples
    for e in entries:
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser_v2.py", line 470, in parse
    yield from self.parse_handle(handle)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser_v2.py", line 483, in parse_handle
    yield from self._parse_issues(model)
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser_v2.py", line 501, in _parse_issues
    issue, callable, callable_position, "sink"
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser_v2.py", line 561, in _parse_issue_conditions
    method=Method.from_json(origin),
  File "/home/rong/.venvs/mariana-trench/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser_v2.py", line 53, in from_json
    canonical_name = method["name"]
KeyError: 'name'

`$ pip list | grep sapp`
fb-sapp             0.5.4

Looking forward to hearing from you.
Thanks!

**Comment by arthaud** [comment]
Hi @mwmarry,
This is most likely due to a mismatch between fb-sapp and mariana-trench. Please make sure you are using the last version of those two packages.
For instance, the latest version of fb-sapp is [0.5.6](https://pypi.org/project/fb-sapp/#history).

If you still have issues after upgrading, please provide us with the version of fb-sapp and mariana-trench you are using.
I might need to push a new upgrade to one of those.

**Comment by mwmarry** [comment]
Thanks for your reply, the new python and fb-sapp versions can work.
