### ISSUE TITLE
Error by following Getting Started

### ISSUE THREAD

**Issue by linghuiluo** [facebook/mariana-trench#40]
Hi, 
I was trying your tool out by following the Getting Started section in README.md, but got the following error.  Any hint about how to resolve this issue?
```
(mariana-trench) linghuiluo@Linghuis-MacBook-Pro sample-app %mariana-trench --system-jar-configuration-path=$ANDROID_SDK/platforms/android-30/android.jar --apk-path=sample-app-debug.apk
Password:
INFO Extracting `/Users/linghuiluo/Projects/mariana-trench/documentation/sample-app/sample-app-debug.apk`...
INFO Extracted APK into `/tmp/tmp1pzy08bd_apk` and DEX into `/tmp/tmptl0_emvd_dex`
INFO Running Mariana Trench: /Users/linghuiluo/.venvs/mariana-trench/bin/mariana-trench-binary --system-jar-paths /Users/linghuiluo/Library/Android/sdk/platforms/android-30/android.jar --apk-directory /tmp/tmp1pzy08bd_apk --dex-directory /tmp/tmptl0_emvd_dex --rules-paths /Users/linghuiluo/.venvs/mariana-trench/share/mariana-trench/configuration/rules.json --repository-root-directory /Users/linghuiluo/Projects/mariana-trench/documentation/sample-app/ --source-root-directory /Users/linghuiluo/Projects/mariana-trench/documentation/sample-app/ --apk-path /Users/linghuiluo/Projects/mariana-trench/documentation/sample-app/sample-app-debug.apk --output-directory /Users/linghuiluo/Projects/mariana-trench/documentation/sample-app/ --maximum-source-sink-distance 7 --model-generator-configuration-paths /Users/linghuiluo/.venvs/mariana-trench/share/mariana-trench/configuration/default_generator_config.json --model-generator-search-paths /Users/linghuiluo/.venvs/mariana-trench/share/mariana-trench/configuration/model-generators
CRITICAL Unexpected error:
Traceback (most recent call last):
  File "/Users/linghuiluo/.venvs/mariana-trench/lib/python3.8/site-packages/mariana_trench/shim/shim.py", line 576, in main
    output = subprocess.run(command)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/linghuiluo/.venvs/mariana-trench/bin/mariana-trench-binary'
```

**Comment by OctavianGuzu** [comment]
Hello, I was getting the same error.

To fix it: I left the Python venv and installed the package directly using "pip3". Installing mariana-trench with pip3 solved the error for me

**Comment by linghuiluo** [comment]
@OctavianGuzu Thanks! Reinstall with pip3 worked.
