### ISSUE TITLE
get "KeyError: 'caller_port'" when using sapp

### ISSUE THREAD

**Issue by xiaoxiongwang** [facebook/mariana-trench#92]
# Bug
**Bug description**
When using:
```
sapp --tool=mariana-trench analyze .
```
I got error:
/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Run.issue_instances to refer to viewonly relationship IssueInstance.run should include sync_backref=False set on the Run.issue_instances relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship IssueInstance.run to refer to viewonly relationship Run.issue_instances should include sync_backref=False set on the IssueInstance.run relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
2022-05-23 09:04:16,316 [INFO] Parsing analysis output...
Traceback (most recent call last):
  File "/home/test/ftool/mariana-trench/build/venv/bin/sapp", line 8, in <module>
    sys.exit(cli())
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/cli_lib.py", line 208, in analyze
    pipeline.run(analysis_output, summary_blob)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/pipeline/__init__.py", line 363, in run
    next_input, summary = step.run(next_input, summary)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/pipeline/base_parser.py", line 239, in run
    summary.get("old_linemap_file"),
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/pipeline/base_parser.py", line 188, in analysis_output_to_dict_entries
    for typ, key, e in self._analysis_output_to_parsed_tuples(inputfile):
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/pipeline/base_parser.py", line 135, in _analysis_output_to_parsed_tuples
    for e in entries:
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser.py", line 351, in parse
    yield from self.parse_handle(handle)
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser.py", line 365, in parse_handle
    for precondition in self._parse_precondition(model):
  File "/home/test/ftool/mariana-trench/build/venv/lib/python3.7/site-packages/sapp/pipeline/mariana_trench_parser.py", line 500, in _parse_precondition
    port=Port.from_json(sink["caller_port"], "sink"),
KeyError: 'caller_port'

Looking forward to hearing from you.
Thanks!

**Comment by jalee0606** [comment]
Hi @xiaoxiongwang, I encountered the same problem as you. I think the only way to fix it is either wait for a newer release on pip or run the SAPP directly from source and modify the cli.py to target the v2 parser in the pipeline. The new parser generate a different structure sapp.db file, so you might also need the latest version to run the server.

It seemed that the MT might have generated a different format of json. https://github.com/facebook/sapp/commit/465e09f9a9a5b2a0af3ba58f1f18a333e226e22e

**Comment by koftnt** [comment]
got same issue @jalee0606 . It don't work for me by setting the value to true in Constants.h of mariana-trench  then rebuild.

**Comment by jalee0606** [comment]
> got same issue @jalee0606 . It don't work for me by setting the value to true in Constants.h of mariana-trench then rebuild.

I tested it, I set it to true, build and run it. I managed to analyze it with the sapp from pip.

**Comment by jalee0606** [comment]
> > > got same issue @jalee0606 . It don't work for me by setting the value to true in Constants.h of mariana-trench then rebuild.
> > 
> > 
> > I tested it, I set it to true, build and run it. I managed to analyze it with the sapp from pip.
> 
> @jalee0606 Did you rebuild all staffs including redex or just mariana? Do I need clean all compiler-generated objects first?

Nope. I only build just mariana.

`make -j4`
`make install`

**Comment by sinancepel** [comment]
Mariana Trench 1.0.3 is out, which should resolve this issue by default! Sorry about the long delay here.
